# Default values for steadybit-extension-crud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  # image.name -- The container image to use for the steadybit CRUD extension.
  name: ghcr.io/steadybit/extension-crud
  # image.tag -- tag name of the extension-crud container image to use.
  # See https://hub.docker.com/r/steadybit/extension-crud for all tags.
  tag: latest
  # image.pullPolicy -- Specifies when to pull the image container.
  pullPolicy: Always

tls:
  server:
    certificate:
      # tls.server.certificate.fromSecret -- The name of the secret containing the TLS certificate for the extension.
      #  The extension will then create an HTTPS server instead of an HTTP server.
      fromSecret: null
      # tls.server.certificate.path --Path to the TLS certificate for the extension.
      path: null
      key:
        # tls.server.certificate.key-path --Path to the key for the TLS certificate for the extension.
        path: null
  client:
    certificates:
      # tls.client.certificates.fromSecrets -- List of secret names containing TLS certificates for the extension to trust.
      #  The extension will require clients to authenticate using one of these certificates. In essence, this will enable mutual TLS.
      fromSecrets: []
      # tls.client.certificates.paths -- List paths containing TLS certificates for the extension to trust.
      #  The extension will require clients to authenticate using one of these certificates. In essence, this will enable mutual TLS.
      paths: []
logging:
  # logging.level -- The active log level. Valid values are: TRACE, DEBUG, INFO, WARN, ERROR
  level: INFO
  # logging.format -- The format of the log entries. One of text, json
  format: text

crud:
  # crud.instanceName -- Description name for this CRUD extension instance. Results in a created target attribute.
  instanceName: "Dog Shelter"
  # crud.targetType -- The technical key of the targets created through this extension.
  targetType: "dog"
  # crud.targetTypeLabel -- The human-readable label of the target type created through this extension.
  targetTypeLabel: "Dog"

resources:
  requests:
    # resources.requests.memory -- The minimal amount of memory needed
    memory: "64Mi"
    # resources.requests.cpu -- The minimal amount of cpu shares needed
    cpu: "50m"
  limits:
    # resources.limits.memory -- The limit of memory to be used
    memory: "128Mi"
    # resources.limits.cpu -- The limit of cpu share to be used during its interval
    cpu: "200m"

# extra labels to apply to the Kubernetes resources
extraLabels: {}

# nodeSelector -- Node labels for pod assignment
nodeSelector: {}

# tolerations -- Tolerations to influence pod assignment
tolerations: []

# topologySpreadConstraints -- Spread constraints to influence pod assignment.
# https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
topologySpreadConstraints: []

# affinity -- Affinities to influence pod assignment.
affinity: {}
