apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "extensionlib.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "extensionlib.names.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "extensionlib.names.fullname" . }}
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: extension-crud
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            - name: STEADYBIT_EXTENSION_PORT
              value: "8080"
            {{- include "extensionlib.deployment.env" (list .) | nindent 12 }}
            - name: STEADYBIT_EXTENSION_INSTANCE_NAME
              value: {{ .Values.crud.instanceName | quote }}
            - name: STEADYBIT_EXTENSION_TARGET_TYPE
              value: {{ .Values.crud.targetType | quote }}
            - name: STEADYBIT_EXTENSION_TARGET_TYPE_LABEL
              value: {{ .Values.crud.targetTypeLabel | quote }}
          volumeMounts:
            {{- include "extensionlib.deployment.volumeMounts" (list .) | nindent 12 }}
      volumes:
        {{- include "extensionlib.deployment.volumes" (list .) | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}